### ISSUE TITLE
Brought extra 'UR' for segment CUR after prettify

### ISSUE THREAD

**Issue by nevertomorrow** [Silvenga/vscode-edi-x12-support#12]
When I tried to prettify a 856 doc, I found the last CUR segment turned into CURUR.

Original: 

`SAC*C*I134***10127808~CUR*CM*USD~CTT*868*1728~SE*5218*261060410`

After prettify:
`SAC*C*I134***10127808~`
`CURUR*CM*USD~`
`CTT*868*1728~`
`SE*5218*261060410~`

**Comment by Silvenga** [comment]
I can't reproduce, can you provide a scrubbed ISA header?

**Comment by nevertomorrow** [comment]
Hi, Silvenga

Please try this one. 

`ISA*00*          *00*          *ZZ*ZZZPBLAP       *ZZ*ABCDEFGDGE     *190105*1619*U*00501*369190516*0*P*:~GS*SH*ZZZPBLAP*ABCDEFGDGE*20190105*1619*368190516*X*005010~ST*856*051619363~BSN*00*67480518*20190105*1616*0001~DTM*011*20190105*1145*08~DTM*110*20190105*0830*08~DTM*140*20190105*1050*08~HL*1**S~TD1*PLT*1****G*444.60*KG~TD1*CTN*235****G*444.600*KG~TD5**2*APX~SAC*C*I134***7697190~CUR*CM*USD~CTT*235~SE*4267*051619363~GE*1*368190516~IEA*1*369190516~`

I tried from my end and I got
`ISA*00*          *00*          *ZZ*ZZZPBLAP       *ZZ*ABCDEFGDGE     *190105*1619*U*00501*369190516*0*P*:~`
`GS*SH*ZZZPBLAP*ABCDEFGDGE*20190105*1619*368190516*X*005010~`
`ST*856*051619363~`
`BSN*00*67480518*20190105*1616*0001~`
`DTM*011*20190105*1145*08~`
`DTM*110*20190105*0830*08~`
`DTM*140*20190105*1050*08~`
`HL*1**S~`
`TD1*PLT*1****G*444.60*KG~`
`TD1*CTN*235****G*444.600*KG~`
`TD5**2*APX~`
`SAC*C*I134***7697190~`
`CURUR*CM*USD~`
`CTT*235~`
`SE*4267*051619363~`
`GE*1*368190516~`
`IEA*1*369190516~`

Thanks.

**Comment by Silvenga** [comment]
It looks like the ISA header may be invalid. Should the repeating separator be `U`? Normally that value can't exist within segment ids e.g. `CUR`. This explains the weirdness.

**Comment by nevertomorrow** [comment]
Hi, Silvenga

You're right, it seems like my partner just use "U" for ISA11 and that is for version 4010, now since they declared it as 5010, ISA11 should be the repetition separator. Your plugin works correctly after I change the U to ^.

Thanks again and I'll close the issue.
