### ISSUE TITLE
Add option to set the file extensions for which parsing is active

### ISSUE THREAD

**Issue by bluejorts** [Silvenga/vscode-edi-x12-support#5]
Right now, this extension only supports the file extension `.edi`.
Having the option to also, for instance, parse `.270` or `.271` files would be very useful.
I'd also be happy to submit a PR if someone could point me to where the file extension settings are in the source, since I haven't had experience with VSCode extensions in the past.

**Comment by Silvenga** [comment]
Hey @Polymetric! - that would be great, I always appreciate pull requests.

If you want, you can add extensions to this array:

https://github.com/Silvenga/vscode-edi-x12-support/blob/master/package.json#L45

**Comment by bluejorts** [comment]
https://github.com/Silvenga/vscode-edi-x12-support/pull/6

**Comment by Silvenga** [comment]
Resolved via #6.

Unfortunately VSCode does not support dynamic language support at this time. That said, custom languages can be mapped via user settings (and on a per file settings via the language context menu, which cannot be accessed programmatically at this time).

`.270` and `.271` are common extensions, so I think adding them is valid.

Closing for now.
